### ISSUE TITLE
How can be setted the value programatically?

### ISSUE THREAD

**Issue by ramiroaisen** [qintarp/svelte-color-picker#1]
I need to update the value programatically, how can i do that?

**Comment by qintarp** [comment]
This is not currently possible and I am afraid I am a bit busy for a while to add this functionality, although I'd be happy to review and accept a pull request.

**Comment by ramiroaisen** [comment]
I make a fork of it, i change all the document.querySelector for the bind:this svelte declaration and i add the setColor method you can see it in ramiroaisen/svelte-picker
