### ISSUE TITLE
Input hex/RGB not working

### ISSUE THREAD

**Issue by arperyan** [qintarp/svelte-color-picker#5]
Hi,

The input for hex/RGB is not allowing you to change the values. I have tried the example page and my own app, with no luck.

Many Thanks,

Ryan Arpe

**Comment by arperyan** [comment]
Hi @qintarp,

Have you got an update on the color picker?

Ryan Arpe

**Comment by qintarp** [comment]
Hello,

That functionality currently does not exist, I am afraid I currently don't have enough time to implement it myself.

**Comment by arperyan** [comment]
Ok. Thanks for the reply.
