### ISSUE TITLE
Feature request : Permit multiple color pickers on same page

### ISSUE THREAD

**Issue by infuzz** [qintarp/svelte-color-picker#7]
Hello; your colorpicker is really awesome ! thx for that !
I would suggest a feature request:

Scope all mouse events to the component itself rather that to the global document, to permit to have several colorpicker in the same page

you could use 
let me;
and  in the first div:
<div bind:this={me}  >
 and change 'document.' by 'me.' everywhere execept  for 
    document.addEventListener("mouseup", mouseUp);
    document.addEventListener("touchend", mouseUp);
to let them handle end of select when mouse goes outside of color picker....

If you could have a look on this.
Thx.

**Comment by qintarp** [comment]
Hi,
Sorry for the late reply, although I don't exactly recall what kind, iirc scoping all mouse events to the component itself was causing problems. I'm afraid I currently don't have time to work on this issue to resolve it in some way. But I'd be happy to review a pull requests if someone else decides to work on it.

**Comment by infuzz** [comment]
Thx for your answer, I'll will try to work on it
